# model settings
model : 'resnet18'

# dataset settings
data_root : '/data/user/cephfs/lincolnlin/dataset/cifar10/'
mean : [0.4914, 0.4822, 0.4465]
std : [0.2023, 0.1994, 0.2010]
batch_size : 64

# optimizer and learning rate
optimizer : 
    type : SGD
    lr : 0.1
    momentum : 0.9
    weight_decay : 5.0e-4

optimizer_config :
    #grad_clip : None

lr_config : 
    policy : step
    step : 2

# runtime settings
work_dir : './demo'
gpus : [0,3]
data_workers : 2  # data workers per gpu
checkpoint_config :
    interval : 1
 
workflow : 
    - !!python/tuple ['train', 1]
    - !!python/tuple ['val', 1]

total_epochs :  6
#resume_from :
#load_from :

# logging settings
log_level : 'INFO'
log_config :
    interval : 50
    hooks:
        [ type : TextLoggerHook ]
